In [1]:
import json
import pandas as pd

import plotly.express as px

In [2]:
import os

os.chdir("..")

In [3]:
from pathlib import Path

def process_run(run_dir: Path):
    df = None
    params = None

    for fname in run_dir.rglob("*.csv"):
        df = pd.read_csv(fname)

    for fname in run_dir.rglob("**/params.json"):
        with open(fname) as f:
            params = json.load(f)

    return df["val_acc"].max(), df["train_loss"].min(), params["train_loop_config"]

In [17]:
target_dir = Path("ray_results")

results = []

for run_dir in target_dir.glob("TorchTrainer_2025-03-16_1*"):

    try:
        f1, loss, params = process_run(run_dir)
        probe_type = params["probe_type"]
        n_shift_tokens = params["n_shift_tokens"]
        n_prev_tokens = params["n_prev_tokens"]
        tgt_action = params.get("tgt_action", 0)

        results.append({
            "f1": f1,
            "loss": loss,
            "probe type": probe_type,
            "n_shift_tokens": abs(n_shift_tokens),
            # "n_prev_tokens": n_prev_tokens,
            "tgt_action": tgt_action
        })
    except:
        pass

In [18]:
df = pd.DataFrame.from_records(results)

df

          f1      loss probe type  n_shift_tokens  tgt_action
0   0.626866  0.679199       mlha             100           1
1   0.205882  1.364063       mlha             100           7
2   0.462687  0.479785        gru             100           0
3   0.268657  0.654297       mlha             200           3
4   0.477612  0.437012       mlha             200           0
5   0.298507  1.158594       mlha             100           2
6   0.268657  1.078906       mlha             100           3
7   0.205882  0.755859       mlha             200           5
8   0.343284  0.774219       mlha             400           0
9   0.313433  0.488086       mlha             300           0
10  0.328358  0.693555       mlha             200           2
11  0.235294  0.697363       mlha             200           7
12  0.477612  0.300879        gru             100           0
13  0.686567  0.617090       mlha             100           0
14  0.323529  0.819336       mlha             200           4
15  0.283582  1.077930       mlha             100           0
16  0.358209  0.642676       mlha             400           0
17  0.264706  1.259375       mlha             100           4
18  0.308824  1.365625       mlha             100           6
19  0.298507  0.670898       mlha             400           0
20  0.308824  1.148438       mlha             100           5
21  0.220588  0.391113       mlha            1900           7
22  0.328358  0.577344       mlha             300           1
23  0.671642  0.687305       mlha             100           0
24  0.626866  0.659668       mlha             100           0
25  0.279412  0.858984       mlha             200           6
26  0.671642  0.719922       mlha             100           0
27  0.388060  1.031641        gru             100           0
28  0.492537  0.650977       mlha             200           0
29  0.507463  0.459570       mlha             200           1
30  0.253731  1.789844       mlha             100           0
31  0.731343  0.788281       mlha             100           0
32  0.626866  0.788086       mlha             100           0

In [16]:
df[df["tgt_action"] == 0]

           f1      loss probe type  n_shift_tokens  tgt_action
25   0.328358  0.355566       mlha             800           0
27   0.313433  0.437207       mlha             700           0
37   0.253731  0.388867       mlha            1800           0
42   0.194030  0.353223       mlha            1400           0
48   0.194030  0.404102       mlha            1100           0
50   0.223881  0.450391       mlha             900           0
56   0.194030  0.379834       mlha            1900           0
66   0.238806  0.490527       mlha             500           0
75   0.164179  0.282080       mlha            1700           0
77   0.194030  0.459375       mlha             600           0
79   0.238806  0.372461       mlha            1000           0
91   0.238806  0.402344       mlha            1600           0
96   0.208955  0.374023       mlha            1500           0
99   0.223881  0.408203       mlha            1200           0
100  0.253731  0.494922       mlha             400           0
126  0.223881  0.374512       mlha            1300           0